version: '3.4'

x-common-env-variables: &common-env-variables
  NODE_ENV: development-docker

services:
  pokedex:
    image: rodarte/nestjs-fr-pokedex-dev:1aae241
    volumes:
      - ./pokedex:/node/app
      - /node/app/node_modules
    environment:
      <<: *common-env-variables
  pokedex-mongodb:
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    volumes:
      - ./pokedex/mongo/dev:/data/db
