version: '3.4'

x-common-env-variables: &common-env-variables
  NODE_ENV: production-docker

services:
  pokedex:
    image: rodarte/nestjs-fr-pokedex-prod:67a7381
    ports:
      - '3000:3000'
    environment:
      <<: *common-env-variables
      PORT: 3000
      MONGODB_URL_FILE_PATH: /run/secrets/pokedex_mongodb_url
      POKEMON_SEED_API: https://pokeapi.co/api/v2/pokemon
      POKEMON_SEED_LIMIT: 650
    secrets:
      - pokedex_mongodb_url
    depends_on:
      - pokedex-mongodb
  pokedex-mongodb:
    image: mongo:5.0
    volumes:
      - ./pokedex/mongo/prod:/data/db

secrets:
  pokedex_mongodb_url:
    file: ./secrets/docker/pokedex/mongodb-url.txt
